
export const LandPlantListPageSelectors = {
 

    //column headers
    plantCodeHeader: "[data-testid='plantCode-header']",
    someIntValHeader: "[data-testid='someIntVal-header']",
    someBigIntValHeader: "[data-testid='someBigIntVal-header']",
    someBitValHeader: "[data-testid='someBitVal-header']",
    isEditAllowedHeader: "[data-testid='isEditAllowed-header']",
    isDeleteAllowedHeader: "[data-testid='isDeleteAllowed-header']",
    someFloatValHeader: "[data-testid='someFloatVal-header']",
    someDecimalValHeader: "[data-testid='someDecimalVal-header']",
    someUTCDateTimeValHeader: "[data-testid='someUTCDateTimeVal-header']",
    someDateValHeader: "[data-testid='someDateVal-header']",
    someMoneyValHeader: "[data-testid='someMoneyVal-header']",
    someNVarCharValHeader: "[data-testid='someNVarCharVal-header']",
    someVarCharValHeader: "[data-testid='someVarCharVal-header']",
    someTextValHeader: "[data-testid='someTextVal-header']",
    somePhoneNumberHeader: "[data-testid='somePhoneNumber-header']",
    someEmailAddressHeader: "[data-testid='someEmailAddress-header']",
    flavorNameHeader: "[data-testid='flavorName-header']",
    flavorCodeHeader: "[data-testid='flavorCode-header']",
    someIntConditionalOnDeletableHeader: "[data-testid='someIntConditionalOnDeletable-header']",
    nVarCharAsUrlHeader: "[data-testid='nVarCharAsUrl-header']", 
    updateLinkPlantCodeHeader:  "[data-testid='updateLinkPlantCode-header']",
    deleteAsyncButtonLinkPlantCodeHeader: "[data-testid='deleteAsyncButtonLinkPlantCode-header']",
    detailsLinkPlantCodeHeader: "[data-testid='detailsLinkPlantCode-header']",

    //column headerSortDownIndicator
    plantCodeHeaderSortDownIndicator: "[data-testid='plantCode-header-sortDown']",
    someIntValHeaderSortDownIndicator: "[data-testid='someIntVal-header-sortDown']",
    someBigIntValHeaderSortDownIndicator: "[data-testid='someBigIntVal-header-sortDown']",
    someBitValHeaderSortDownIndicator: "[data-testid='someBitVal-header-sortDown']",
    isEditAllowedHeaderSortDownIndicator: "[data-testid='isEditAllowed-header-sortDown']",
    isDeleteAllowedHeaderSortDownIndicator: "[data-testid='isDeleteAllowed-header-sortDown']",
    someFloatValHeaderSortDownIndicator: "[data-testid='someFloatVal-header-sortDown']",
    someDecimalValHeaderSortDownIndicator: "[data-testid='someDecimalVal-header-sortDown']",
    someUTCDateTimeValHeaderSortDownIndicator: "[data-testid='someUTCDateTimeVal-header-sortDown']",
    someDateValHeaderSortDownIndicator: "[data-testid='someDateVal-header-sortDown']",
    someMoneyValHeaderSortDownIndicator: "[data-testid='someMoneyVal-header-sortDown']",
    someNVarCharValHeaderSortDownIndicator: "[data-testid='someNVarCharVal-header-sortDown']",
    someVarCharValHeaderSortDownIndicator: "[data-testid='someVarCharVal-header-sortDown']",
    someTextValHeaderSortDownIndicator: "[data-testid='someTextVal-header-sortDown']",
    somePhoneNumberHeaderSortDownIndicator: "[data-testid='somePhoneNumber-header-sortDown']",
    someEmailAddressHeaderSortDownIndicator: "[data-testid='someEmailAddress-header-sortDown']",
    flavorNameHeaderSortDownIndicator: "[data-testid='flavorName-header-sortDown']",
    flavorCodeHeaderSortDownIndicator: "[data-testid='flavorCode-header-sortDown']",
    someIntConditionalOnDeletableHeaderSortDownIndicator: "[data-testid='someIntConditionalOnDeletable-header-sortDown']",
    nVarCharAsUrlHeaderSortDownIndicator: "[data-testid='nVarCharAsUrl-header-sortDown']", 
    updateLinkPlantCodeHeaderSortDownIndicator:  "[data-testid='updateLinkPlantCode-header-sortDown']",
    deleteAsyncButtonLinkPlantCodeHeaderSortDownIndicator: "[data-testid='deleteAsyncButtonLinkPlantCode-header-sortDown']",
    detailsLinkPlantCodeHeaderSortDownIndicator: "[data-testid='detailsLinkPlantCode-header-sortDown']",
  
    
    
    //column headerSortUpIndicator
    plantCodeHeaderSortUpIndicator: "[data-testid='plantCode-header-sortUp']",
    someIntValHeaderSortUpIndicator: "[data-testid='someIntVal-header-sortUp']",
    someBigIntValHeaderSortUpIndicator: "[data-testid='someBigIntVal-header-sortUp']",
    someBitValHeaderSortUpIndicator: "[data-testid='someBitVal-header-sortUp']",
    isEditAllowedHeaderSortUpIndicator: "[data-testid='isEditAllowed-header-sortUp']",
    isDeleteAllowedHeaderSortUpIndicator: "[data-testid='isDeleteAllowed-header-sortUp']",
    someFloatValHeaderSortUpIndicator: "[data-testid='someFloatVal-header-sortUp']",
    someDecimalValHeaderSortUpIndicator: "[data-testid='someDecimalVal-header-sortUp']",
    someUTCDateTimeValHeaderSortUpIndicator: "[data-testid='someUTCDateTimeVal-header-sortUp']",
    someDateValHeaderSortUpIndicator: "[data-testid='someDateVal-header-sortUp']",
    someMoneyValHeaderSortUpIndicator: "[data-testid='someMoneyVal-header-sortUp']",
    someNVarCharValHeaderSortUpIndicator: "[data-testid='someNVarCharVal-header-sortUp']",
    someVarCharValHeaderSortUpIndicator: "[data-testid='someVarCharVal-header-sortUp']",
    someTextValHeaderSortUpIndicator: "[data-testid='someTextVal-header-sortUp']",
    somePhoneNumberHeaderSortUpIndicator: "[data-testid='somePhoneNumber-header-sortUp']",
    someEmailAddressHeaderSortUpIndicator: "[data-testid='someEmailAddress-header-sortUp']",
    flavorNameHeaderSortUpIndicator: "[data-testid='flavorName-header-sortUp']",
    flavorCodeHeaderSortUpIndicator: "[data-testid='flavorCode-header-sortUp']",
    someIntConditionalOnDeletableHeaderSortUpIndicator: "[data-testid='someIntConditionalOnDeletable-header-sortUp']",
    nVarCharAsUrlHeaderSortUpIndicator: "[data-testid='nVarCharAsUrl-header-sortUp']", 
    updateLinkPlantCodeHeaderSortUpIndicator:  "[data-testid='updateLinkPlantCode-header-sortUp']",
    deleteAsyncButtonLinkPlantCodeHeaderSortUpIndicator: "[data-testid='deleteAsyncButtonLinkPlantCode-header-sortUp']",
    detailsLinkPlantCodeHeaderSortUpIndicator: "[data-testid='detailsLinkPlantCode-header-sortUp']",
 
        otherAddButton: "[data-testid='otherAddButton']",

    title: "[data-testid='page-title-text']", 
    introText: "[data-testid='page-intro-text']",
     
 
        addButton: "[data-testid='add-button']",
    
    //breadcrumb
    tacFarmDashboardBreadcrumbText: "[data-testid='tacFarmDashboardBreadcrumb']",
  
    //row button text - not ignored
    updateLinkPlantCodeRowButton: "[data-testid='updateLinkPlantCode-column-0-button']",
    deleteAsyncButtonLinkPlantCodeRowButton: "[data-testid='deleteAsyncButtonLinkPlantCode-column-0-button']",
    detailsLinkPlantCodeRowButton: "[data-testid='detailsLinkPlantCode-column-0-button']",

    
        backButton: "[data-testid='back-button']",

    someIntValFilterLabel: "[data-testid='someIntVal-label']",
    someBigIntValFilterLabel: "[data-testid='someBigIntVal-label']",
    someBitValFilterLabel: "[data-testid='someBitVal-label']",
    isEditAllowedFilterLabel: "[data-testid='isEditAllowed-label']",
    isDeleteAllowedFilterLabel: "[data-testid='isDeleteAllowed-label']",
    someFloatValFilterLabel: "[data-testid='someFloatVal-label']",
    someDecimalValFilterLabel: "[data-testid='someDecimalVal-label']",
    someMinUTCDateTimeValFilterLabel: "[data-testid='someMinUTCDateTimeVal-label']",
    someMinDateValFilterLabel: "[data-testid='someMinDateVal-label']",
    someMoneyValFilterLabel: "[data-testid='someMoneyVal-label']",
    someNVarCharValFilterLabel: "[data-testid='someNVarCharVal-label']",
    someVarCharValFilterLabel: "[data-testid='someVarCharVal-label']",
    someTextValFilterLabel: "[data-testid='someTextVal-label']",
    somePhoneNumberFilterLabel: "[data-testid='somePhoneNumber-label']",
    someEmailAddressFilterLabel: "[data-testid='someEmailAddress-label']",
    flavorCodeFilterLabel: "[data-testid='flavorCode-label']",

    
    someIntValFilterField: "[data-testid='someIntVal-field']",
    someBigIntValFilterField: "[data-testid='someBigIntVal-field']",
    someBitValFilterField: "[data-testid='someBitVal-field']",
    isEditAllowedFilterField: "[data-testid='isEditAllowed-field']",
    isDeleteAllowedFilterField: "[data-testid='isDeleteAllowed-field']",
    someFloatValFilterField: "[data-testid='someFloatVal-field']",
    someDecimalValFilterField: "[data-testid='someDecimalVal-field']",
    someMinUTCDateTimeValFilterField: "[data-testid='someMinUTCDateTimeVal-field']",
    someMinDateValFilterField: "[data-testid='someMinDateVal-field']",
    someMoneyValFilterField: "[data-testid='someMoneyVal-field']",
    someNVarCharValFilterField: "[data-testid='someNVarCharVal-field']",
    someVarCharValFilterField: "[data-testid='someVarCharVal-field']",
    someTextValFilterField: "[data-testid='someTextVal-field']",
    somePhoneNumberFilterField: "[data-testid='somePhoneNumber-field']",
    someEmailAddressFilterField: "[data-testid='someEmailAddress-field']",
    flavorCodeFilterField: "[data-testid='flavorCode-field']",
    

    pagingControl: "[data-testid='reportGridLandPlantList-paginator-pageination']",
    pageSizeControl: "[data-testid='reportGridLandPlantList-paginator-pageination-select-page-size']",
    pageSizeControlLabel: "[data-testid='items-per-page-label']",
    tableRowCountDisplay: "[data-testid='reportGridLandPlantList-paginator-pageination-count-display']",
}