
export const LandPlantListPageSelectors = {
 

    //column headers
//endset
    plantCodeHeader: "[data-testid='plantCode-header']",
    someIntValHeader: "[data-testid='someIntVal-header']",
    someConditionalIntValHeader: "[data-testid='someConditionalIntVal-header']",
    someBigIntValHeader: "[data-testid='someBigIntVal-header']",
    someConditionalBigIntValHeader: "[data-testid='someConditionalBigIntVal-header']",
    someBitValHeader: "[data-testid='someBitVal-header']",
    someConditionalBitValHeader: "[data-testid='someConditionalBitVal-header']",
    isEditAllowedHeader: "[data-testid='isEditAllowed-header']",
    isDeleteAllowedHeader: "[data-testid='isDeleteAllowed-header']",
    someFloatValHeader: "[data-testid='someFloatVal-header']",
    someConditionalFloatValHeader: "[data-testid='someConditionalFloatVal-header']",
    someDecimalValHeader: "[data-testid='someDecimalVal-header']",
    someConditionalDecimalValHeader: "[data-testid='someConditionalDecimalVal-header']",
    someUTCDateTimeValHeader: "[data-testid='someUTCDateTimeVal-header']",
    someConditionalUTCDateTimeValHeader: "[data-testid='someConditionalUTCDateTimeVal-header']",
    someDateValHeader: "[data-testid='someDateVal-header']",
    someConditionalDateValHeader: "[data-testid='someConditionalDateVal-header']",
    someMoneyValHeader: "[data-testid='someMoneyVal-header']",
    someConditionalMoneyValHeader: "[data-testid='someConditionalMoneyVal-header']",
    someNVarCharValHeader: "[data-testid='someNVarCharVal-header']",
    someConditionalNVarCharValHeader: "[data-testid='someConditionalNVarCharVal-header']",
    someVarCharValHeader: "[data-testid='someVarCharVal-header']",
    someConditionalVarCharValHeader: "[data-testid='someConditionalVarCharVal-header']",
    someTextValHeader: "[data-testid='someTextVal-header']",
    someConditionalTextValHeader: "[data-testid='someConditionalTextVal-header']",
    somePhoneNumberHeader: "[data-testid='somePhoneNumber-header']",
    someConditionalPhoneNumberHeader: "[data-testid='someConditionalPhoneNumber-header']",
    someEmailAddressHeader: "[data-testid='someEmailAddress-header']",
    someConditionalEmailAddressHeader: "[data-testid='someConditionalEmailAddress-header']",
    flavorNameHeader: "[data-testid='flavorName-header']",
    flavorCodeHeader: "[data-testid='flavorCode-header']",
    someIntConditionalOnDeletableHeader: "[data-testid='someIntConditionalOnDeletable-header']",
    nVarCharAsUrlHeader: "[data-testid='nVarCharAsUrl-header']", 
    nVarCharConditionalAsUrlHeader: "[data-testid='nVarCharConditionalAsUrl-header']", 
    updateLinkPlantCodeHeader:  "[data-testid='updateLinkPlantCode-header']",
    deleteAsyncButtonLinkPlantCodeHeader: "[data-testid='deleteAsyncButtonLinkPlantCode-header']",
    detailsLinkPlantCodeHeader: "[data-testid='detailsLinkPlantCode-header']",
    testFileDownloadLinkPacCodeHeader: "[data-testid='testFileDownloadLinkPacCode-header']",
    testConditionalFileDownloadLinkPacCodeHeader: "[data-testid='testConditionalFileDownloadLinkPacCode-header']",
    testAsyncFlowReqLinkPacCodeHeader: "[data-testid='testAsyncFlowReqLinkPacCode-header']",
    testConditionalAsyncFlowReqLinkPacCodeHeader: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header']",
    conditionalBtnExampleLinkPlantCodeHeader: "[data-testid='conditionalBtnExampleLinkPlantCode-header']",
//endset

    //column headerSortDownIndicator
//endset
    plantCodeHeaderSortDownIndicator: "[data-testid='plantCode-header-sortDown']",
    someIntValHeaderSortDownIndicator: "[data-testid='someIntVal-header-sortDown']",
    someConditionalIntValHeaderSortDownIndicator: "[data-testid='someConditionalIntVal-header-sortDown']",
    someBigIntValHeaderSortDownIndicator: "[data-testid='someBigIntVal-header-sortDown']",
    someConditionalBigIntValHeaderSortDownIndicator: "[data-testid='someConditionalBigIntVal-header-sortDown']",
    someBitValHeaderSortDownIndicator: "[data-testid='someBitVal-header-sortDown']",
    someConditionalBitValHeaderSortDownIndicator: "[data-testid='someConditionalBitVal-header-sortDown']",
    isEditAllowedHeaderSortDownIndicator: "[data-testid='isEditAllowed-header-sortDown']",
    isDeleteAllowedHeaderSortDownIndicator: "[data-testid='isDeleteAllowed-header-sortDown']",
    someFloatValHeaderSortDownIndicator: "[data-testid='someFloatVal-header-sortDown']",
    someConditionalFloatValHeaderSortDownIndicator: "[data-testid='someConditionalFloatVal-header-sortDown']",
    someDecimalValHeaderSortDownIndicator: "[data-testid='someDecimalVal-header-sortDown']",
    someConditionalDecimalValHeaderSortDownIndicator: "[data-testid='someConditionalDecimalVal-header-sortDown']",
    someUTCDateTimeValHeaderSortDownIndicator: "[data-testid='someUTCDateTimeVal-header-sortDown']",
    someConditionalUTCDateTimeValHeaderSortDownIndicator: "[data-testid='someConditionalUTCDateTimeVal-header-sortDown']",
    someDateValHeaderSortDownIndicator: "[data-testid='someDateVal-header-sortDown']",
    someConditionalDateValHeaderSortDownIndicator: "[data-testid='someConditionalDateVal-header-sortDown']",
    someMoneyValHeaderSortDownIndicator: "[data-testid='someMoneyVal-header-sortDown']",
    someConditionalMoneyValHeaderSortDownIndicator: "[data-testid='someConditionalMoneyVal-header-sortDown']",
    someNVarCharValHeaderSortDownIndicator: "[data-testid='someNVarCharVal-header-sortDown']",
    someConditionalNVarCharValHeaderSortDownIndicator: "[data-testid='Conditional-header-sortDown']",
    someVarCharValHeaderSortDownIndicator: "[data-testid='someVarCharVal-header-sortDown']",
    someConditionalVarCharValHeaderSortDownIndicator: "[data-testid='someConditionalVarCharVal-header-sortDown']",
    someTextValHeaderSortDownIndicator: "[data-testid='someTextVal-header-sortDown']",
    someConditionalTextValHeaderSortDownIndicator: "[data-testid='someConditionalTextVal-header-sortDown']",
    somePhoneNumberHeaderSortDownIndicator: "[data-testid='somePhoneNumber-header-sortDown']",
    someConditionalPhoneNumberHeaderSortDownIndicator: "[data-testid='someConditionalPhoneNumber-header-sortDown']",
    someEmailAddressHeaderSortDownIndicator: "[data-testid='someEmailAddress-header-sortDown']",
    someConditionalEmailAddressHeaderSortDownIndicator: "[data-testid='someConditionalEmailAddress-header-sortDown']",
    flavorNameHeaderSortDownIndicator: "[data-testid='flavorName-header-sortDown']",
    flavorCodeHeaderSortDownIndicator: "[data-testid='flavorCode-header-sortDown']",
    someIntConditionalOnDeletableHeaderSortDownIndicator: "[data-testid='someIntConditionalOnDeletable-header-sortDown']",
    nVarCharAsUrlHeaderSortDownIndicator: "[data-testid='nVarCharAsUrl-header-sortDown']", 
    nVarCharConditionalAsUrlHeaderSortDownIndicator: "[data-testid='nVarCharConditionalAsUrl-header-sortDown']", 
    updateLinkPlantCodeHeaderSortDownIndicator:  "[data-testid='updateLinkPlantCode-header-sortDown']",
    deleteAsyncButtonLinkPlantCodeHeaderSortDownIndicator: "[data-testid='deleteAsyncButtonLinkPlantCode-header-sortDown']",
    detailsLinkPlantCodeHeaderSortDownIndicator: "[data-testid='detailsLinkPlantCode-header-sortDown']", 
    testFileDownloadLinkPacCodeHeaderSortDownIndicator: "[data-testid='testFileDownloadLinkPacCode-header-sortDown']",
    testConditionalFileDownloadLinkPacCodeHeaderSortDownIndicator: "[data-testid='testConditionalFileDownloadLinkPacCode-header-sortDown']",
    testAsyncFlowReqLinkPacCodeHeaderSortDownIndicator: "[data-testid='testAsyncFlowReqLinkPacCode-header-sortDown']",
    testConditionalAsyncFlowReqLinkPacCodeHeaderSortDownIndicator: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header-sortDown']",
    conditionalBtnExampleLinkPlantCodeHeaderSortDownIndicator: "[data-testid='conditionalBtnExampleLinkPlantCode-header-sortDown']",
//endset
  
    
    
    //column headerSortUpIndicator
//endset
    plantCodeHeaderSortUpIndicator: "[data-testid='plantCode-header-sortUp']",
    someIntValHeaderSortUpIndicator: "[data-testid='someIntVal-header-sortUp']",
    someConditionalIntValHeaderSortUpIndicator: "[data-testid='someConditionalIntVal-header-sortUp']",
    someBigIntValHeaderSortUpIndicator: "[data-testid='someBigIntVal-header-sortUp']",
    someConditionalBigIntValHeaderSortUpIndicator: "[data-testid='someConditionalBigIntVal-header-sortUp']",
    someBitValHeaderSortUpIndicator: "[data-testid='someBitVal-header-sortUp']",
    isEditAllowedHeaderSortUpIndicator: "[data-testid='isEditAllowed-header-sortUp']",
    isDeleteAllowedHeaderSortUpIndicator: "[data-testid='isDeleteAllowed-header-sortUp']",
    someFloatValHeaderSortUpIndicator: "[data-testid='someFloatVal-header-sortUp']",
    someConditionalFloatValHeaderSortUpIndicator: "[data-testid='someConditionalFloatVal-header-sortUp']",
    someDecimalValHeaderSortUpIndicator: "[data-testid='someDecimalVal-header-sortUp']",
    someConditionalDecimalValHeaderSortUpIndicator: "[data-testid='someConditionalDecimalVal-header-sortUp']",
    someUTCDateTimeValHeaderSortUpIndicator: "[data-testid='someUTCDateTimeVal-header-sortUp']",
    someConditionalUTCDateTimeValHeaderSortUpIndicator: "[data-testid='someConditionalUTCDateTimeVal-header-sortUp']",
    someDateValHeaderSortUpIndicator: "[data-testid='someDateVal-header-sortUp']",
    someConditionalDateValHeaderSortUpIndicator: "[data-testid='someConditionalDateVal-header-sortUp']",
    someMoneyValHeaderSortUpIndicator: "[data-testid='someMoneyVal-header-sortUp']",
    someConditionalMoneyValHeaderSortUpIndicator: "[data-testid='someConditionalMoneyVal-header-sortUp']",
    someNVarCharValHeaderSortUpIndicator: "[data-testid='someNVarCharVal-header-sortUp']",
    someConditionalNVarCharValHeaderSortUpIndicator: "[data-testid='someConditionalNVarCharVal-header-sortUp']",
    someVarCharValHeaderSortUpIndicator: "[data-testid='someVarCharVal-header-sortUp']",
    someConditionalVarCharValHeaderSortUpIndicator: "[data-testid='someConditionalVarCharVal-header-sortUp']",
    someTextValHeaderSortUpIndicator: "[data-testid='someTextVal-header-sortUp']",
    someConditionalTextValHeaderSortUpIndicator: "[data-testid='someConditionalTextVal-header-sortUp']",
    somePhoneNumberHeaderSortUpIndicator: "[data-testid='somePhoneNumber-header-sortUp']",
    someConditionalPhoneNumberHeaderSortUpIndicator: "[data-testid='someConditionalPhoneNumber-header-sortUp']",
    someEmailAddressHeaderSortUpIndicator: "[data-testid='someEmailAddress-header-sortUp']",
    someConditionalEmailAddressHeaderSortUpIndicator: "[data-testid='someConditionalEmailAddress-header-sortUp']",
    flavorNameHeaderSortUpIndicator: "[data-testid='flavorName-header-sortUp']",
    flavorCodeHeaderSortUpIndicator: "[data-testid='flavorCode-header-sortUp']",
    someIntConditionalOnDeletableHeaderSortUpIndicator: "[data-testid='someIntConditionalOnDeletable-header-sortUp']",
    nVarCharAsUrlHeaderSortUpIndicator: "[data-testid='nVarCharAsUrl-header-sortUp']", 
    nVarCharConditionalAsUrlHeaderSortUpIndicator: "[data-testid='nVarCharConditionalAsUrl-header-sortUp']", 
    updateLinkPlantCodeHeaderSortUpIndicator:  "[data-testid='updateLinkPlantCode-header-sortUp']",
    deleteAsyncButtonLinkPlantCodeHeaderSortUpIndicator: "[data-testid='deleteAsyncButtonLinkPlantCode-header-sortUp']",
    detailsLinkPlantCodeHeaderSortUpIndicator: "[data-testid='detailsLinkPlantCode-header-sortUp']",
    testFileDownloadLinkPacCodeHeaderSortUpIndicator: "[data-testid='testFileDownloadLinkPacCode-header-sortUp']",
    testConditionalFileDownloadLinkPacCodeHeaderSortUpIndicator: "[data-testid='testConditionalFileDownloadLinkPacCode-header-sortUp']",
    testAsyncFlowReqLinkPacCodeHeaderSortUpIndicator: "[data-testid='testAsyncFlowReqLinkPacCode-header-sortUp']",
    testConditionalAsyncFlowReqLinkPacCodeHeaderSortUpIndicator: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header-sortUp']",
    conditionalBtnExampleLinkPlantCodeHeaderSortUpIndicator: "[data-testid='conditionalBtnExampleLinkPlantCode-header-sortUp']",
//endset
 
    otherAddButton: "[data-testid='otherAddButton']",

    title: "[data-testid='page-title-text']", 
    introText: "[data-testid='page-intro-text']",
     
 
    addButton: "[data-testid='add-button']",
    
    //breadcrumb
    tacFarmDashboardBreadcrumbText: "[data-testid='tacFarmDashboardBreadcrumb']",
  
    //row button text - not ignored
    updateLinkPlantCodeRowButton: "[data-testid='updateLinkPlantCode-column-0-button']",
    deleteAsyncButtonLinkPlantCodeRowButton: "[data-testid='deleteAsyncButtonLinkPlantCode-column-0-button']",
    detailsLinkPlantCodeRowButton: "[data-testid='detailsLinkPlantCode-column-0-button']",
    testFileDownloadLinkPacCodeRowButton: "[data-testid='testFileDownloadLinkPacCode-column-0-button']",
    testConditionalFileDownloadLinkPacCodeRowButton: "[data-testid='testConditionalFileDownloadLinkPacCode-column-0-button']",
    testAsyncFlowReqLinkPacCodeRowButton: "[data-testid='testAsyncFlowReqLinkPacCode-column-0-button']",
    testConditionalAsyncFlowReqLinkPacCodeRowButton: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-column-0-button']",
    conditionalBtnExampleLinkPlantCodeRowButton: "[data-testid='conditionalBtnExampleLinkPlantCode-column-0-button']",

    
        backButton: "[data-testid='back-button']",

    someIntValFilterLabel: "[data-testid='someIntVal-label']",
    someBigIntValFilterLabel: "[data-testid='someBigIntVal-label']",
    someBitValFilterLabel: "[data-testid='someBitVal-label']",
    isEditAllowedFilterLabel: "[data-testid='isEditAllowed-label']",
    isDeleteAllowedFilterLabel: "[data-testid='isDeleteAllowed-label']",
    someFloatValFilterLabel: "[data-testid='someFloatVal-label']",
    someDecimalValFilterLabel: "[data-testid='someDecimalVal-label']",
    someMinUTCDateTimeValFilterLabel: "[data-testid='someMinUTCDateTimeVal-label']",
    someMinDateValFilterLabel: "[data-testid='someMinDateVal-label']",
    someMoneyValFilterLabel: "[data-testid='someMoneyVal-label']",
    someNVarCharValFilterLabel: "[data-testid='someNVarCharVal-label']",
    someVarCharValFilterLabel: "[data-testid='someVarCharVal-label']",
    someTextValFilterLabel: "[data-testid='someTextVal-label']",
    somePhoneNumberFilterLabel: "[data-testid='somePhoneNumber-label']",
    someEmailAddressFilterLabel: "[data-testid='someEmailAddress-label']",
    flavorCodeFilterLabel: "[data-testid='flavorCode-label']",

    
    someIntValFilterField: "[data-testid='someIntVal-field']",
    someBigIntValFilterField: "[data-testid='someBigIntVal-field']",
    someBitValFilterField: "[data-testid='someBitVal-field']",
    isEditAllowedFilterField: "[data-testid='isEditAllowed-field']",
    isDeleteAllowedFilterField: "[data-testid='isDeleteAllowed-field']",
    someFloatValFilterField: "[data-testid='someFloatVal-field']",
    someDecimalValFilterField: "[data-testid='someDecimalVal-field']",
    someMinUTCDateTimeValFilterField: "[data-testid='someMinUTCDateTimeVal-field']",
    someMinDateValFilterField: "[data-testid='someMinDateVal-field']",
    someMoneyValFilterField: "[data-testid='someMoneyVal-field']",
    someNVarCharValFilterField: "[data-testid='someNVarCharVal-field']",
    someVarCharValFilterField: "[data-testid='someVarCharVal-field']",
    someTextValFilterField: "[data-testid='someTextVal-field']",
    somePhoneNumberFilterField: "[data-testid='somePhoneNumber-field']",
    someEmailAddressFilterField: "[data-testid='someEmailAddress-field']",
    flavorCodeFilterField: "[data-testid='flavorCode-field']",
    

    pagingControl: "[data-testid='reportGridLandPlantList-paginator-pagination']",
    pageSizeControl: "[data-testid='reportGridLandPlantList-paginator-pagination-select-page-size']",
    pageSizeControlLabel: "[data-testid='items-per-page-label']",
    tableRowCountDisplay: "[data-testid='reportGridLandPlantList-paginator-pagination-count-display']",

    filterHeader: "[data-testid='reportConnectedLandPlantList-filter-header']",

    siteFooter: "[data-testid='footer-text']",

    filterSearchButton: "[data-testid='submit-button']",
    filterRefreshButton: "[data-testid='reset']",
}