export const PlantEditPageSelectors = {
    flavorCodeLabel: "[data-testid='flavorCode-label']",
    otherFlavorLabel: "[data-testid='otherFlavor-label']",
    someIntValLabel: "[data-testid='someIntVal-label']",
    someBigIntValLabel: "[data-testid='someBigIntVal-label']",
    someBitValLabel: "[data-testid='someBitVal-label']",
    isEditAllowedLabel: "[data-testid='isEditAllowed-label']",
    isDeleteAllowedLabel: "[data-testid='isDeleteAllowed-label']",
    someFloatValLabel: "[data-testid='someFloatVal-label']",
    someDecimalValLabel: "[data-testid='someDecimalVal-label']",
    someUTCDateTimeValLabel: "[data-testid='someUTCDateTimeVal-label']",
    someDateValLabel: "[data-testid='someDateVal-label']",
    someMoneyValLabel: "[data-testid='someMoneyVal-label']",
    someNVarCharValLabel: "[data-testid='someNVarCharVal-label']",
    someVarCharValLabel: "[data-testid='someVarCharVal-label']",
    someTextValLabel: "[data-testid='someTextVal-label']",
    somePhoneNumberLabel: "[data-testid='somePhoneNumber-label']",
    someEmailAddressLabel: "[data-testid='someEmailAddress-label']",
    flavorCodeField: "[data-testid='flavorCode']",
    otherFlavorField: "[data-testid='otherFlavor']",
    someIntValField: "[data-testid='someIntVal']",
    someBigIntValField: "[data-testid='someBigIntVal']",
    someBitValField: "[data-testid='someBitVal']",
    isEditAllowedField: "[data-testid='isEditAllowed']",
    isDeleteAllowedField: "[data-testid='isDeleteAllowed']",
    someFloatValField: "[data-testid='someFloatVal']",
    someDecimalValField: "[data-testid='someDecimalVal']",
    someUTCDateTimeValField: "[data-testid='someUTCDateTimeVal']",
    someDateValField: "[data-testid='someDateVal']",
    someMoneyValField: "[data-testid='someMoneyVal']",
    someNVarCharValField: "[data-testid='someNVarCharVal']",
    someVarCharValField: "[data-testid='someVarCharVal']",
    someTextValField: "[data-testid='someTextVal']",
    somePhoneNumberField: "[data-testid='somePhoneNumber']",
    someEmailAddressField: "[data-testid='someEmailAddress']",
    //page title
    title: "[data-testid='page-title-text']",
    //page intro text
    introText: "[data-testid='page-intro-text']",
    footerText: "[data-testid='page-footer-text']",
    submitButton: "[data-testid='submit-button']",
    cancelButton: "[data-testid='cancel-button']",

}

