
export const PlantUserDetailsPageSelectors = {
    flavorNameHeader: "[data-testid='flavorName-header']",
    isDeleteAllowedHeader: "[data-testid='isDeleteAllowed-header']",
    isEditAllowedHeader: "[data-testid='isEditAllowed-header']",
    otherFlavorHeader: "[data-testid='otherFlavor-header']",
    someBigIntValHeader: "[data-testid='someBigIntVal-header']",
    someBitValHeader: "[data-testid='someBitVal-header']",
    someDateValHeader: "[data-testid='someDateVal-header']",
    someDecimalValHeader: "[data-testid='someDecimalVal-header']",
    someEmailAddressHeader: "[data-testid='someEmailAddress-header']",
    someFloatValHeader: "[data-testid='someFloatVal-header']",
    someIntValHeader: "[data-testid='someIntVal-header']",
    someMoneyValHeader: "[data-testid='someMoneyVal-header']",
    someNVarCharValHeader: "[data-testid='someNVarCharVal-header']",
    somePhoneNumberHeader: "[data-testid='somePhoneNumber-header']",
    someTextValHeader: "[data-testid='someTextVal-header']",
    someUTCDateTimeValHeader: "[data-testid='someUTCDateTimeVal-header']",
    someVarCharValHeader: "[data-testid='someVarCharVal-header']",
    phoneNumConditionalOnIsEditableHeader: "[data-testid='phoneNumConditionalOnIsEditable-header']",
    nVarCharAsUrlHeader: "[data-testid='nVarCharAsUrl-header']",
    updateButtonTextLinkPlantCodeHeader:  "[data-testid='updateButtonTextLinkPlantCode-header']",
    randomPropertyUpdatesLinkPlantCodeHeader: "[data-testid='randomPropertyUpdatesLinkPlantCode-header']",
    backToDashboardLinkTacCodeHeader: "[data-testid='backToDashboardLinkTacCode-header']",
    testFileDownloadLinkPacCodeHeader: "[data-testid='testFileDownloadLinkPacCode-header']",
    testConditionalAsyncFileDownloadLinkPacCodeHeader: "[data-testid='testConditionalAsyncFileDownloadLinkPacCode-header']",
    testAsyncFlowReqLinkPacCodeHeader: "[data-testid='testAsyncFlowReqLinkPacCode-header']",
    testConditionalAsyncFlowReqLinkPacCodeHeader: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header']",
    conditionalBtnExampleLinkTacCodeHeader: "[data-testid='conditionalBtnExampleLinkTacCode-header']",
//endset
    someImageUrlValHeader: "[data-testid='someImageUrlVal-header']",
    isImageUrlAvailableHeader: "[data-testid='isImageUrlAvailable-header']",
    someConditionalImageUrlValHeader: "[data-testid='someConditionalImageUrlVal-header']",
    flavorNameHeaderSortDownIndicator: "[data-testid='flavorName-header-sortDown']",
    isDeleteAllowedHeaderSortDownIndicator: "[data-testid='isDeleteAllowed-header-sortDown']",
    isEditAllowedHeaderSortDownIndicator: "[data-testid='isEditAllowed-header-sortDown']",
    otherFlavorHeaderSortDownIndicator: "[data-testid='otherFlavor-header-sortDown']",
    someBigIntValHeaderSortDownIndicator: "[data-testid='someBigIntVal-header-sortDown']",
    someBitValHeaderSortDownIndicator: "[data-testid='someBitVal-header-sortDown']",
    someDateValHeaderSortDownIndicator: "[data-testid='someDateVal-header-sortDown']",
    someDecimalValHeaderSortDownIndicator: "[data-testid='someDecimalVal-header-sortDown']",
    someEmailAddressHeaderSortDownIndicator: "[data-testid='someEmailAddress-header-sortDown']",
    someFloatValHeaderSortDownIndicator: "[data-testid='someFloatVal-header-sortDown']",
    someIntValHeaderSortDownIndicator: "[data-testid='someIntVal-header-sortDown']",
    someMoneyValHeaderSortDownIndicator: "[data-testid='someMoneyVal-header-sortDown']",
    someNVarCharValHeaderSortDownIndicator: "[data-testid='someNVarCharVal-header-sortDown']",
    somePhoneNumberHeaderSortDownIndicator: "[data-testid='somePhoneNumber-header-sortDown']",
    someTextValHeaderSortDownIndicator: "[data-testid='someTextVal-header-sortDown']",
    someUTCDateTimeValHeaderSortDownIndicator: "[data-testid='someUTCDateTimeVal-header-sortDown']",
    someVarCharValHeaderSortDownIndicator: "[data-testid='someVarCharVal-header-sortDown']",
    phoneNumConditionalOnIsEditableHeaderSortDownIndicator: "[data-testid='phoneNumConditionalOnIsEditable-header-sortDown']",
    nVarCharAsUrlHeaderSortDownIndicator: "[data-testid='nVarCharAsUrl-header-sortDown']",
    updateButtonTextLinkPlantCodeHeaderSortDownIndicator:  "[data-testid='updateButtonTextLinkPlantCode-header-sortDown']",
    randomPropertyUpdatesLinkPlantCodeHeaderSortDownIndicator: "[data-testid='randomPropertyUpdatesLinkPlantCode-header-sortDown']",
    backToDashboardLinkTacCodeHeaderSortDownIndicator: "[data-testid='backToDashboardLinkTacCode-header-sortDown']",
    testFileDownloadLinkPacCodeHeaderSortDownIndicator: "[data-testid='testFileDownloadLinkPacCode-header-sortDown']",
    testConditionalAsyncFileDownloadLinkPacCodeHeaderSortDownIndicator: "[data-testid='testConditionalAsyncFileDownloadLinkPacCode-header-sortDown']",
    testAsyncFlowReqLinkPacCodeHeaderSortDownIndicator: "[data-testid='testAsyncFlowReqLinkPacCode-header-sortDown']",
    testConditionalAsyncFlowReqLinkPacCodeHeaderSortDownIndicator: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header-sortDown']",
    conditionalBtnExampleLinkTacCodeHeaderSortDownIndicator: "[data-testid='conditionalBtnExampleLinkTacCode-header-sortDown']",
//endset
    someImageUrlValHeaderSortDownIndicator: "[data-testid='someImageUrlVal-header-sortDown']",
    isImageUrlAvailableHeaderSortDownIndicator: "[data-testid='isImageUrlAvailable-header-sortDown']",
    someConditionalImageUrlValHeaderSortDownIndicator: "[data-testid='someConditionalImageUrlVal-header-sortDown']",
    flavorNameHeaderSortUpIndicator: "[data-testid='flavorName-header-sortUp']",
    isDeleteAllowedHeaderSortUpIndicator: "[data-testid='isDeleteAllowed-header-sortUp']",
    isEditAllowedHeaderSortUpIndicator: "[data-testid='isEditAllowed-header-sortUp']",
    otherFlavorHeaderSortUpIndicator: "[data-testid='otherFlavor-header-sortUp']",
    someBigIntValHeaderSortUpIndicator: "[data-testid='someBigIntVal-header-sortUp']",
    someBitValHeaderSortUpIndicator: "[data-testid='someBitVal-header-sortUp']",
    someDateValHeaderSortUpIndicator: "[data-testid='someDateVal-header-sortUp']",
    someDecimalValHeaderSortUpIndicator: "[data-testid='someDecimalVal-header-sortUp']",
    someEmailAddressHeaderSortUpIndicator: "[data-testid='someEmailAddress-header-sortUp']",
    someFloatValHeaderSortUpIndicator: "[data-testid='someFloatVal-header-sortUp']",
    someIntValHeaderSortUpIndicator: "[data-testid='someIntVal-header-sortUp']",
    someMoneyValHeaderSortUpIndicator: "[data-testid='someMoneyVal-header-sortUp']",
    someNVarCharValHeaderSortUpIndicator: "[data-testid='someNVarCharVal-header-sortUp']",
    somePhoneNumberHeaderSortUpIndicator: "[data-testid='somePhoneNumber-header-sortUp']",
    someTextValHeaderSortUpIndicator: "[data-testid='someTextVal-header-sortUp']",
    someUTCDateTimeValHeaderSortUpIndicator: "[data-testid='someUTCDateTimeVal-header-sortUp']",
    someVarCharValHeaderSortUpIndicator: "[data-testid='someVarCharVal-header-sortUp']",
    phoneNumConditionalOnIsEditableHeaderSortUpIndicator: "[data-testid='phoneNumConditionalOnIsEditable-header-sortUp']",
    nVarCharAsUrlHeaderSortUpIndicator: "[data-testid='nVarCharAsUrl-header-sortUp']",
    updateButtonTextLinkPlantCodeHeaderSortUpIndicator:  "[data-testid='updateButtonTextLinkPlantCode-header-sortUp']",
    randomPropertyUpdatesLinkPlantCodeHeaderSortUpIndicator: "[data-testid='randomPropertyUpdatesLinkPlantCode-header-sortUp']",
    backToDashboardLinkTacCodeHeaderSortUpIndicator: "[data-testid='backToDashboardLinkTacCode-header-sortUp']",
    testFileDownloadLinkPacCodeHeaderSortUpIndicator: "[data-testid='testFileDownloadLinkPacCode-header-sortUp']",
    testConditionalAsyncFileDownloadLinkPacCodeHeaderSortUpIndicator: "[data-testid='testConditionalAsyncFileDownloadLinkPacCode-header-sortUp']",
    testAsyncFlowReqLinkPacCodeHeaderSortUpIndicator: "[data-testid='testAsyncFlowReqLinkPacCode-header-sortUp']",
    testConditionalAsyncFlowReqLinkPacCodeHeaderSortUpIndicator: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-header-sortUp']",
    conditionalBtnExampleLinkTacCodeHeaderSortUpIndicator: "[data-testid='conditionalBtnExampleLinkTacCode-header-sortUp']",
//endset
    someImageUrlValHeaderSortUpIndicator: "[data-testid='someImageUrlVal-header-sortUp']",
    isImageUrlAvailableHeaderSortUpIndicator: "[data-testid='isImageUrlAvailable-header-sortUp']",
    someConditionalImageUrlValHeaderSortUpIndicator: "[data-testid='someConditionalImageUrlVal-header-sortUp']",

    title: "[data-testid='page-title-text']",
    introText: "[data-testid='page-intro-text']",
    //breadcrumb
    tacFarmDashboardBreadcrumbText: "[data-testid='tacFarmDashboardBreadcrumb']",
    //breadcrumb
    landPlantListBreadcrumbText: "[data-testid='landPlantListBreadcrumb']",
    //row button text - not ignored
    updateButtonTextLinkPlantCodeRowButton: "[data-testid='updateButtonTextLinkPlantCode-column-0-button']",
    randomPropertyUpdatesLinkPlantCodeRowButton: "[data-testid='randomPropertyUpdatesLinkPlantCode-column-0-button']",
    backToDashboardLinkTacCodeRowButton: "[data-testid='backToDashboardLinkTacCode-column-0-button']",
    testFileDownloadLinkPacCodeRowButton: "[data-testid='testFileDownloadLinkPacCode-column-0-button']",
    testConditionalAsyncFileDownloadLinkPacCodeRowButton: "[data-testid='testConditionalAsyncFileDownloadLinkPacCode-column-0-button']",
    testAsyncFlowReqLinkPacCodeRowButton: "[data-testid='testAsyncFlowReqLinkPacCode-column-0-button']",
    testConditionalAsyncFlowReqLinkPacCodeRowButton: "[data-testid='testConditionalAsyncFlowReqLinkPacCode-column-0-button']",
    conditionalBtnExampleLinkTacCodeRowButton: "[data-testid='conditionalBtnExampleLinkTacCode-column-0-button']",
        backButton: "[data-testid='back-button']",

    pagingControl: "[data-testid='reportGridPlantUserDetails-paginator-pagination']",
    pageSizeControl: "[data-testid='reportGridPlantUserDetails-paginator-pagination-select-page-size']",
    pageSizeControlLabel: "[data-testid='items-per-page-label']",
    tableRowCountDisplay: "[data-testid='reportGridPlantUserDetails-paginator-pagination-count-display']",

    filterHeader: "[data-testid='reportConnectedPlantUserDetails-filter-header']",

    siteFooter: "[data-testid='footer-text']",

    filterSearchButton: "[data-testid='submit-button']",
    filterRefreshButton: "[data-testid='reset']",
}

