
export const LandPlantListPageSettings = {

    
    calculatedIsVisualizationGrid: true,

//endset
    plantCodeHeaderIsVisible: true,
    someIntValHeaderIsVisible: true, 
    someConditionalIntValHeaderIsVisible: true, 
    someBigIntValHeaderIsVisible: true,
    someConditionalBigIntValHeaderIsVisible: true,
    someBitValHeaderIsVisible: true,
    someConditionalBitValHeaderIsVisible: true,
    isEditAllowedHeaderIsVisible: true,
    isDeleteAllowedHeaderIsVisible: true,
    someFloatValHeaderIsVisible: true,
    someConditionalFloatValHeaderIsVisible: true,
    someDecimalValHeaderIsVisible: true,
    someConditionalDecimalValHeaderIsVisible: true,
    someUTCDateTimeValHeaderIsVisible: true,
    someConditionalUTCDateTimeValHeaderIsVisible: true,
    someDateValHeaderIsVisible: true,
    someConditionalDateValHeaderIsVisible: true,
    someMoneyValHeaderIsVisible: true,
    someConditionalMoneyValHeaderIsVisible: true,
    someNVarCharValHeaderIsVisible: true,
    someConditionalNVarCharValHeaderIsVisible: true,
    someVarCharValHeaderIsVisible: true,
    someConditionalVarCharValHeaderIsVisible: true,
    someTextValHeaderIsVisible: true,
    someConditionalTextValHeaderIsVisible: true,
    somePhoneNumberHeaderIsVisible: true,
    someConditionalPhoneNumberHeaderIsVisible: true,
    someEmailAddressHeaderIsVisible: true,
    someConditionalEmailAddressHeaderIsVisible: true,
    flavorNameHeaderIsVisible: true,
    flavorCodeHeaderIsVisible: false,
    someIntConditionalOnDeletableHeaderIsVisible: true,
    nVarCharAsUrlHeaderIsVisible: true,
    nVarCharConditionalAsUrlHeaderIsVisible: true,
    updateLinkPlantCodeHeaderIsVisible: false,
    deleteAsyncButtonLinkPlantCodeHeaderIsVisible: true,
    detailsLinkPlantCodeHeaderIsVisible: true,
    testFileDownloadLinkPacCodeHeaderIsVisible: true,
    testConditionalFileDownloadLinkPacCodeHeaderIsVisible: true,
    testAsyncFlowReqLinkPacCodeHeaderIsVisible: true,
    testConditionalAsyncFlowReqLinkPacCodeHeaderIsVisible: true,
    conditionalBtnExampleLinkPlantCodeHeaderIsVisible: true,
//endset

    
    isFilterSectionHidden: false,
    
    someIntValIsVisible: true,
    someBigIntValIsVisible: true,
    someBitValIsVisible: true,
    isEditAllowedIsVisible: true,
    isDeleteAllowedIsVisible: true,
    someFloatValIsVisible: true,
    someDecimalValIsVisible: true,
    someMinUTCDateTimeValIsVisible: true,
    someMinDateValIsVisible: true,
    someMoneyValIsVisible: true,
    someNVarCharValIsVisible: true,
    someVarCharValIsVisible: true,
    someTextValIsVisible: true,
    somePhoneNumberIsVisible: true,
    someEmailAddressIsVisible: true,
    flavorCodeIsVisible: true, 
     
} 
