
export const LandPlantListPageSettings = {

    
    calculatedIsVisualizationGrid: true,

//endset
    plantCodeHeaderIsVisible: true,
    someIntValHeaderIsVisible: true, 
    someConditionalIntValHeaderIsVisible: true, 
    someBigIntValHeaderIsVisible: true,
    someConditionalBigIntValHeaderIsVisible: true,
    someBitValHeaderIsVisible: true,
    someConditionalBitValHeaderIsVisible: true,
    isEditAllowedHeaderIsVisible: true,
    isDeleteAllowedHeaderIsVisible: true,
    someFloatValHeaderIsVisible: true,
    someConditionalFloatValHeaderIsVisible: true,
    someDecimalValHeaderIsVisible: true,
    someConditionalDecimalValHeaderIsVisible: true,
    someUTCDateTimeValHeaderIsVisible: true,
    someConditionalUTCDateTimeValHeaderIsVisible: true,
    someDateValHeaderIsVisible: true,
    someConditionalDateValHeaderIsVisible: true,
    someMoneyValHeaderIsVisible: true,
    someConditionalMoneyValHeaderIsVisible: true,
    someNVarCharValHeaderIsVisible: true,
    someConditionalNVarCharValHeaderIsVisible: true,
    someVarCharValHeaderIsVisible: true,
    someConditionalVarCharValHeaderIsVisible: true,
    someTextValHeaderIsVisible: true,
    someConditionalTextValHeaderIsVisible: true,
    somePhoneNumberHeaderIsVisible: true,
    someConditionalPhoneNumberHeaderIsVisible: true,
    someEmailAddressHeaderIsVisible: true,
    someConditionalEmailAddressHeaderIsVisible: true,
    isImageUrlAvailableHeaderIsVisible: false,
    someImageUrlValHeaderIsVisible: true,
    someConditionalImageUrlHeaderIsVisible: true,
    flavorNameHeaderIsVisible: true,
    flavorCodeHeaderIsVisible: false,
    someIntConditionalOnDeletableHeaderIsVisible: true,
    nVarCharAsUrlHeaderIsVisible: true,
    nVarCharConditionalAsUrlHeaderIsVisible: true,
    updateLinkPlantCodeHeaderIsVisible: false,
    deleteAsyncButtonLinkPlantCodeHeaderIsVisible: true,
    detailsLinkPlantCodeHeaderIsVisible: true,
    testFileDownloadLinkPacCodeHeaderIsVisible: true,
    testConditionalFileDownloadLinkPacCodeHeaderIsVisible: true,
    testAsyncFlowReqLinkPacCodeHeaderIsVisible: true,
    testConditionalAsyncFlowReqLinkPacCodeHeaderIsVisible: true,
    conditionalBtnExampleLinkPlantCodeHeaderIsVisible: true,
//endset

    
    isFilterSectionHidden: false,
    
//endset
    someFilterIntValIsVisible: true,
    someFilterBigIntValIsVisible: true,
    someFilterBitValIsVisible: true,
    isFilterEditAllowedIsVisible: true,
    isFilterDeleteAllowedIsVisible: true,
    someFilterFloatValIsVisible: true,
    someFilterDecimalValIsVisible: true,
    someMinUTCDateTimeValIsVisible: true,
    someMinDateValIsVisible: true,
    someFilterMoneyValIsVisible: true,
    someFilterNVarCharValIsVisible: true,
    someFilterVarCharValIsVisible: true,
    someFilterTextValIsVisible: true,
    someFilterPhoneNumberIsVisible: true,
    someFilterEmailAddressIsVisible: true,
    someFilterUniqueIdentifierIsVisible: true,
    flavorFilterCodeIsVisible: true, 
//endset
     
} 
