
export const LandAddPlantPageSettings = {
    requestFlavorCodeIsVisible: true,
    requestOtherFlavorIsVisible: true,
    requestSomeIntValIsVisible: true,
    requestSomeBigIntValIsVisible: true,
    requestSomeBitValIsVisible: true,
    requestIsEditAllowedIsVisible: true,
    requestIsDeleteAllowedIsVisible: true,
    requestSomeFloatValIsVisible: true,
    requestSomeDecimalValIsVisible: true,
    requestSomeUTCDateTimeValIsVisible: true,
    requestSomeDateValIsVisible: true,
    requestSomeMoneyValIsVisible: true,
    requestSomeNVarCharValIsVisible: true,
    requestSomeLongNVarCharValIsVisible: true,
    requestSomeVarCharValIsVisible: true,
    requestSomeLongVarCharValIsVisible: true,
    requestSomeTextValIsVisible: true,
    requestSomePhoneNumberIsVisible: true,
    requestSomeEmailAddressIsVisible: true,
    requestSampleImageUploadFileIsVisible: true,
    someImageUrlValIsVisible: true,
 
} 